---

include:
  - template: SAST.gitlab-ci.yml

stages:
  - lint
  - test
  - deploy

bash:
  stage: lint
  image: koalaman/shellcheck-alpine
  script:
    - shellcheck --shell=bash import.bash tests/commons.sh

python:
  stage: lint
  image: python:latest
  allow_failure: True
  before_script:
    - pip install prospector[with_everything] defusedxml
  script:
    - make lint

sast:
  stage: lint

.script: &script
  stage: test
  script:
    - mkdir -p ~/.local/share/keyrings/
    - cp tests/assets/db/gnome-keyring.keyring ~/.local/share/keyrings/pass-import.keyring
    - pip3 install --upgrade green coverage defusedxml pyaml cryptography pykeepass secretstorage
    - make
    - dbus-run-session -- make tests
    - make install
    - cd ~
    - pass import --help

.only: &only
  only:
   - tags
   - web

archlinux:
  image: archlinux/base
  before_script:
    - pacman -Syu --noconfirm --noprogressbar which grep make python-pip pass dbus gnome-keyring
  artifacts:
    expire_in: 2 days
    paths:
      - htmlcov/
  <<: *script

ubuntu:
  image: ubuntu
  before_script:
    - apt-get update -q && apt-get install -y make pass python3-pip grep dbus gnome-keyring
  <<: *script
  <<: *only

debian:
  image: debian
  before_script:
    - apt-get update -q && apt-get install -y make pass python3-pip grep wget dbus gnome-keyring
    - wget https://git.zx2c4.com/password-store/snapshot/password-store-1.7.3.tar.xz
    - tar -xf password-store-1.7.3.tar.xz
    - make --directory=password-store-1.7.3 install
  <<: *script
  <<: *only

fedora:
  image: fedora
  before_script:
    - dnf -y install make gpg pass python3-pip grep which dbus dbus-daemon gnome-keyring --setopt=install_weak_deps=False
  <<: *script
  <<: *only

pages:
  stage: deploy
  dependencies:
    - archlinux
  script:
    - mv htmlcov/ public/
  artifacts:
    expire_in: 2 days
    paths:
      - public
  only:
    - master
